# Generated by Django 5.0.6 on 2024-05-30 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tavsif', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FoydalanuvchiMalumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon_raqami', models.CharField(max_length=20)),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jami_summasi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yetkazib_berish', models.BooleanField(default=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashyo.foydalanuvchimalumot')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tavsif', models.TextField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='mahsulot_rasmlar/')),
                ('mavjud', models.BooleanField(default=True)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='ashyo.kategoriya')),
            ],
        ),
        migrations.CreateModel(
            name='BuyurtmaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemlar', to='ashyo.buyurtma')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashyo.mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='YagonaSahifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontent', models.TextField()),
                ('boshqa_mahsulotlar', models.ManyToManyField(blank=True, related_name='boshqa_mahsulotlar', to='ashyo.mahsulot')),
                ('mahsulot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ashyo.mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='YetkazibBerishManzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=100)),
                ('tuman', models.CharField(max_length=100)),
                ('manzil', models.TextField()),
                ('buyurtma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ashyo.buyurtma')),
            ],
        ),
    ]
