# Generated by Django 4.2.13 on 2024-06-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
