# Generated by Django 5.0.6 on 2024-06-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salom',
        ),
    ]
