# Generated by Django 5.0.6 on 2024-06-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_discounted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
