# Generated by Django 5.0.6 on 2024-06-07 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('month', models.PositiveIntegerField()),
                ('percentage', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_payment', to='ashyo.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
