# Generated by Django 5.0.6 on 2024-06-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0002_alter_client_address_alter_client_first_name_and_more'),
        ('ashyo', '0002_client_text_alter_client_email_alter_client_phone'),
    ]

    operations = [
    ]
