# Generated by Django 5.0.6 on 2024-06-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0002_termpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_number_of_views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
