# Generated by Django 5.0.6 on 2024-05-31 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0002_aboutashyo_category_characteristics_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
        migrations.CreateModel(
            name='ProductInfoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ashyo.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('info_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashyo.productinfotype')),
            ],
        ),
        migrations.DeleteModel(
            name='Characteristics',
        ),
    ]
