# Generated by Django 5.0.6 on 2024-06-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0003_product_count_number_of_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
