# Generated by Django 4.2.13 on 2024-06-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0003_remove_product_characteristics_productinfotype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batary',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
