# Generated by Django 5.0.6 on 2024-06-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0005_address_faq_lokatsiya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
    ]
