# Generated by Django 5.0.6 on 2024-06-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0006_alter_comment_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='order',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
        migrations.AddField(
            model_name='productinfodata',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ashyo.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinfodata',
            name='info_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productinfotype', to='ashyo.productinfotype'),
        ),
    ]
