# Generated by Django 5.0.6 on 2024-06-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0007_category_img_product_model_alter_product_category'),
        ('ashyo', '0007_remove_productincart_order_category_image_and_more'),
    ]

    operations = [
    ]
