# Generated by Django 5.0.6 on 2024-06-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashyo', '0008_merge_20240602_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
    ]
